# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1741545049);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1741544805);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1741636923);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1741544929);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1741547660);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.frecency_experiment", 4);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.link.open_newwindow", 2);
user_pref("browser.migration.version", 27);
user_pref("browser.newtabpage.enhanced", false);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.offline-apps.notify", false);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.preferences.advanced.selectedTabIndex", 1);
user_pref("browser.search.countryCode", "US");
user_pref("browser.search.defaultenginename.US", "DuckDuckGo");
user_pref("browser.search.region", "US");
user_pref("browser.search.suggest.enabled", false);
user_pref("browser.search.update", false);
user_pref("browser.sessionstore.restore_on_demand", false);
user_pref("browser.sessionstore.resume_from_crash", false);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20160318181316");
user_pref("browser.slowStartup.averageTime", 0);
user_pref("browser.slowStartup.samples", 0);
user_pref("browser.startup.homepage", "http://localhost");
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.tabs.warnOnOpen", false);
user_pref("devtools.browserconsole.filter.", true);
user_pref("devtools.browserconsole.filter.cssparser", true);
user_pref("devtools.browserconsole.filter.exception", false);
user_pref("devtools.browserconsole.filter.jslog", false);
user_pref("devtools.browserconsole.filter.jswarn", false);
user_pref("devtools.browserconsole.filter.networkinfo", true);
user_pref("devtools.browserconsole.filter.netxhr", true);
user_pref("devtools.gcli.hideIntro", true);
user_pref("devtools.telemetry.tools.opened.version", "{\"DEVTOOLS_TOOLBOX_OPENED_PER_USER_FLAG\":\"38.7.1\",\"DEVTOOLS_INSPECTOR_OPENED_PER_USER_FLAG\":\"38.7.1\",\"DEVTOOLS_RULEVIEW_OPENED_PER_USER_FLAG\":\"38.7.1\",\"DEVTOOLS_NETMONITOR_OPENED_PER_USER_FLAG\":\"38.7.1\",\"DEVTOOLS_WEBCONSOLE_OPENED_PER_USER_FLAG\":\"38.7.1\",\"DEVTOOLS_CUSTOM_OPENED_PER_USER_FLAG\":\"38.7.1\",\"DEVTOOLS_BROWSERCONSOLE_OPENED_PER_USER_FLAG\":\"38.7.1\",\"DEVTOOLS_JSDEBUGGER_OPENED_PER_USER_FLAG\":\"38.7.1\",\"DEVTOOLS_STYLEEDITOR_OPENED_PER_USER_FLAG\":\"38.7.1\",\"DEVTOOLS_DEVELOPERTOOLBAR_OPENED_PER_USER_FLAG\":\"38.7.1\"}");
user_pref("devtools.toolbox.footer.height", 383);
user_pref("devtools.toolbox.selectedTool", "jsdebugger");
user_pref("devtools.toolsidebar-width.inspector", 0);
user_pref("devtools.toolsidebar-width.netmonitor", 0);
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountTotal", 52);
user_pref("extensions.blocklist.pingCountVersion", 52);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:38.7.1");
user_pref("extensions.getAddons.cache.lastUpdate", 1545291913);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "38.7.1");
user_pref("extensions.lastPlatformVersion", "38.7.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/iceweasel/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"38.7.1\",\"st\":1460124731000,\"mt\":1458550831000}}}");
user_pref("gecko.buildID", "20160318181316");
user_pref("gecko.mstone", "38.7.1");
user_pref("general.warnOnAboutConfig", false);
user_pref("idle.lastDailyNotification", 1741636987);
user_pref("media.gmp-manager.buildID", "20160318181316");
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1541135812);
user_pref("places.history.expiration.transient_current_max_pages", 19281);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("security.OCSP.enabled", 0);
user_pref("security.default_personal_cert", "Select Automatically");
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.clients.lastSyncLocal", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.migrated", true);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("services.sync.tabs.lastSyncLocal", "0");
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1540277539);
user_pref("toolkit.startup.last_success", 1741637563);
user_pref("toolkit.telemetry.previousBuildID", "20160318181316");
