#!/bin/sh -e

if [ "$1" = "remove" ]; then
    dpkg-divert --package iceweasel --rename --remove /usr/bin/firefox
fi

# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/common/duckduckgo.xml -- "$@"
# End automatically added section
# Automatically added by dh_installmenu
if [ -x "`which update-menus 2>/dev/null`" ]; then update-menus ; fi
# End automatically added section

