# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1473960122);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1473960242);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1474052056);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1473960002);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1474295847);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 4);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 27);
user_pref("browser.newtabpage.enhanced", false);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.search.countryCode", "US");
user_pref("browser.search.region", "US");
user_pref("browser.sessionstore.resume_from_crash", false);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20160318181316");
user_pref("browser.slowStartup.averageTime", 7149);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage", "http://localhost");
user_pref("devtools.telemetry.tools.opened.version", "{\"DEVTOOLS_TOOLBOX_OPENED_PER_USER_FLAG\":\"38.7.1\",\"DEVTOOLS_INSPECTOR_OPENED_PER_USER_FLAG\":\"38.7.1\",\"DEVTOOLS_RULEVIEW_OPENED_PER_USER_FLAG\":\"38.7.1\",\"DEVTOOLS_NETMONITOR_OPENED_PER_USER_FLAG\":\"38.7.1\",\"DEVTOOLS_WEBCONSOLE_OPENED_PER_USER_FLAG\":\"38.7.1\"}");
user_pref("devtools.toolsidebar-width.inspector", 0);
user_pref("devtools.toolsidebar-width.netmonitor", 0);
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountTotal", 10);
user_pref("extensions.blocklist.pingCountVersion", 10);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:38.7.1");
user_pref("extensions.getAddons.cache.lastUpdate", 1473960123);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "38.7.1");
user_pref("extensions.lastPlatformVersion", "38.7.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/iceweasel/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"38.7.1\",\"st\":1460124731000,\"mt\":1458550831000}}}");
user_pref("gecko.buildID", "20160318181316");
user_pref("gecko.mstone", "38.7.1");
user_pref("general.warnOnAboutConfig", false);
user_pref("idle.lastDailyNotification", 1474295881);
user_pref("media.gmp-manager.buildID", "20160318181316");
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1473874567);
user_pref("places.history.expiration.transient_current_max_pages", 24270);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1473874567);
user_pref("toolkit.startup.last_success", 1474380515);
user_pref("toolkit.telemetry.previousBuildID", "20160318181316");
